name: "Netlify Scheduled Build"
on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 09:00 UTC
  workflow_dispatch:     # Allows manual triggering too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d {} "https://api.netlify.com/build_hooks/67e72e948102ae44b63efbe0"