name: "Netlify Scheduled Build"
on:
  schedule:
    - cron: "0 14 * * 1"  # 2F 15:00
    - cron: "0 10 * * 3"  # 4f 11:00
    - cron: "0 17 * * 5"  # 6f 18:00
  workflow_dispatch:     # Allows manual triggering too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d {} "https://api.netlify.com/build_hooks/67e72e948102ae44b63efbe0"
